// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnzTsiQPNhwGUw4rZ-S_CDsthmeZmrTc',
    appId: '1:538127073098:web:369900b29f8c7dfc570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    authDomain: 'tech-sprint-62113.firebaseapp.com',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    measurementId: 'G-RYZS5FK8E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_VEhFu3IRy8X1MUgozD3NgtL76312Mmg',
    appId: '1:538127073098:android:6f47501eeea46397570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy93G1bpgZFqidAcManwgfDcjHbvbtRY8',
    appId: '1:538127073098:ios:75c50bc792cc143a570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    iosBundleId: 'com.example.hostel2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy93G1bpgZFqidAcManwgfDcjHbvbtRY8',
    appId: '1:538127073098:ios:75c50bc792cc143a570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    iosBundleId: 'com.example.hostel2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnzTsiQPNhwGUw4rZ-S_CDsthmeZmrTc',
    appId: '1:538127073098:web:369900b29f8c7dfc570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    authDomain: 'tech-sprint-62113.firebaseapp.com',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    measurementId: 'G-RYZS5FK8E6',
  );
}