// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnzTsiQPNhwGUw4rZ-S_CDsthmeZmrTc',
    appId: '1:538127073098:web:50afa86fd68ced1e570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    authDomain: 'tech-sprint-62113.firebaseapp.com',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    measurementId: 'G-T17MXZDBDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_VEhFu3IRy8X1MUgozD3NgtL76312Mmg',
    appId: '1:538127073098:android:1cb7d87a3d64922c570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy93G1bpgZFqidAcManwgfDcjHbvbtRY8',
    appId: '1:538127073098:ios:66e922f8ccacee0e570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    iosBundleId: 'com.example.techSprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy93G1bpgZFqidAcManwgfDcjHbvbtRY8',
    appId: '1:538127073098:ios:66e922f8ccacee0e570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    iosBundleId: 'com.example.techSprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnzTsiQPNhwGUw4rZ-S_CDsthmeZmrTc',
    appId: '1:538127073098:web:51a2db6fe74c4e0d570bb3',
    messagingSenderId: '538127073098',
    projectId: 'tech-sprint-62113',
    authDomain: 'tech-sprint-62113.firebaseapp.com',
    storageBucket: 'tech-sprint-62113.firebasestorage.app',
    measurementId: 'G-FD7L6J7QGG',
  );
}
